#!/bin/bash
set -e

export PGPASSWORD="${POSTGRES_PASSWORD}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "CREATE DATABASE ${POSTGRES_KC_DB}"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "CREATE DATABASE ${USER_SERVICE_DB}"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "CREATE DATABASE ${BUSINESS_SERVICE_DB}"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "CREATE DATABASE ${MEDIA_SERVICE_DB}"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "CREATE DATABASE ${QR_SERVICE_DB}"


psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "
  CREATE USER ${KC_DB_USER} WITH PASSWORD '${KC_DB_PASSWORD}';
  CREATE USER ${USER_SERVICE_USER} WITH PASSWORD '${USER_SERVICE_PASSWORD}';
  CREATE USER ${BUSINESS_SERVICE_USER} WITH PASSWORD '${BUSINESS_SERVICE_PASSWORD}';
  CREATE USER ${MEDIA_SERVICE_USER} WITH PASSWORD '${MEDIA_SERVICE_PASSWORD}';
  CREATE USER ${QR_SERVICE_USER} WITH PASSWORD '${QR_SERVICE_PASSWORD}';
"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${POSTGRES_KC_DB}" -c "
  GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_KC_DB} TO ${KC_DB_USER};
  GRANT ALL ON SCHEMA public TO ${KC_DB_USER};
"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${USER_SERVICE_DB}" -c "
  GRANT ALL PRIVILEGES ON DATABASE ${USER_SERVICE_DB} TO ${USER_SERVICE_USER};
  GRANT ALL ON SCHEMA public TO ${USER_SERVICE_USER};
"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${BUSINESS_SERVICE_DB}" -c "
  GRANT ALL PRIVILEGES ON DATABASE ${BUSINESS_SERVICE_DB} TO ${BUSINESS_SERVICE_USER};
  GRANT ALL ON SCHEMA public TO ${BUSINESS_SERVICE_USER};
"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${MEDIA_SERVICE_DB}" -c "
  GRANT ALL PRIVILEGES ON DATABASE ${MEDIA_SERVICE_DB} TO ${MEDIA_SERVICE_USER};
  GRANT ALL ON SCHEMA public TO ${MEDIA_SERVICE_USER};
"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${QR_SERVICE_DB}" -c "
  GRANT ALL PRIVILEGES ON DATABASE ${QR_SERVICE_DB} TO ${QR_SERVICE_USER};
  GRANT ALL ON SCHEMA public TO ${QR_SERVICE_USER};
"

# Grant REPLICATION privilege for Debezium CDC (Change Data Capture)
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "
  ALTER USER ${USER_SERVICE_USER} WITH REPLICATION;
  ALTER USER ${BUSINESS_SERVICE_USER} WITH REPLICATION;
  ALTER USER ${MEDIA_SERVICE_USER} WITH REPLICATION;
  ALTER USER ${QR_SERVICE_USER} WITH REPLICATION;
"

echo "Databases and users have been created successfully."
echo "REPLICATION privileges granted for CDC (Debezium)."